import * as cheerio from "cheerio";
const API=process.env.API_PUBLIC_URL||"http://api:8080";
const TOKEN=process.env.COLLECTOR_TOKEN||"";
const FALLBACK=Number(process.env.COLLECTOR_INTERVAL_MS||1500);
const auth={"x-collector-token":TOKEN};
async function monitors(){const r=await fetch(API+"/api/collector/monitors",{headers:auth});return r.ok?await r.json():[]}
function num(v){if(typeof v==="number"&&Number.isFinite(v))return v;const n=Number(String(v??"").replace(/[^0-9.-]/g,""));return Number.isFinite(n)?n:null}
function normalize(x){if(!x||typeof x!=="object")return null;const id=String(x.id??x.kufar_id??x.ad_id??x.advert_id??"");const url=String(x.url??x.link??x.href??"");const title=String(x.title??x.name??x.subject??"").trim();if(!/^\d{6,}$/.test(id)||(!url&&!title))return null;const images=Array.isArray(x.images)?x.images.map(v=>typeof v==="string"?v:(v?.url||v?.src)).filter(Boolean).slice(0,10):[];return{kufar_id:id,url:url||"https://www.kufar.by/item/"+id,title:title.slice(0,240),price:num(x.price??x.cost),description:x.description??x.text??null,location:x.location??x.city??x.region??null,images}}
function collect(v,out){if(!v)return;if(Array.isArray(v)){for(const x of v)collect(x,out);return}if(typeof v!=="object")return;const n=normalize(v);if(n)out.set(n.kufar_id,n);for(const x of Object.values(v))if(x&&typeof x==="object")collect(x,out)}
function parseHtml(html,base){const $=cheerio.load(html),out=new Map();$("script").each((_,el)=>{const t=$(el).text().trim();if(!t)return;try{collect(JSON.parse(t),out)}catch{}});$("a[href]").each((_,el)=>{const href=$(el).attr("href")||"";if(!/kufar\.by\//i.test(href))return;const id=(href.match(/(\d{6,})/)||[])[1];if(!id||out.has(id))return;const c=$(el).closest("article,li").first();const raw=(c.text()||$(el).text()).replace(/\s+/g," ").trim();const p=raw.match(/([\d\s]+)\s*(?:BYN|р\.?)\b/i);const imgs=c.find("img").map((_,i)=>$(i).attr("src")||$(i).attr("data-src")).get().filter(Boolean).slice(0,10);out.set(id,{kufar_id:id,url:new URL(href,base).href,title:$(el).text().trim().slice(0,240)||raw.slice(0,240),price:p?num(p[1]):null,description:null,location:null,images:imgs})});return[...out.values()].slice(0,200)}
async function scan(m){try{const r=await fetch(m.url,{headers:{"user-agent":"Mozilla/5.0 (compatible; VELORA/1.0)","accept":"text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8"},redirect:"follow"});if(!r.ok)return;const ct=r.headers.get("content-type")||"";const body=await r.text();const out=new Map();if(ct.includes("json")){try{collect(JSON.parse(body),out)}catch{}}else for(const x of parseHtml(body,m.url))out.set(x.kufar_id,x);await Promise.all([...out.values()].map(x=>fetch(API+"/api/ingest/listing",{method:"POST",headers:{"x-collector-token":TOKEN,"content-type":"application/json"},body:JSON.stringify({...x,monitor_id:m.id,currency:"BYN"})}).catch(()=>{}))}catch(e){console.error("http scan",m.id,e.message)}}
while(true){try{const ms=await monitors();await Promise.all(ms.map(scan));const delay=ms.length?Math.min(...ms.map(m=>Number(m.interval_ms)||FALLBACK)):FALLBACK;await new Promise(r=>setTimeout(r,Math.max(1000,delay)))}catch(e){console.error("loop",e.message);await new Promise(r=>setTimeout(r,FALLBACK))}}